/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import com.alibaba.fastjson.JSONObject;
import toy.utils.MemoryWatcher;
import toy.utils.CPUWatcher;

import toy.learn.FutureCancel;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        MemoryWatcher memWatcher = new MemoryWatcher();
        CPUWatcher cpuWatcher = new CPUWatcher();
        JSONObject memUsageJson = new JSONObject(memWatcher.getUsage());
        JSONObject cpuUsageJson = new JSONObject(cpuWatcher.getUsage());
        System.out.println(String.format("Memory Usage: %s", JSONObject.toJSONString(memUsageJson, true)));
        System.out.println(String.format("CPU Usage: %s", JSONObject.toJSONString(cpuUsageJson, true)));
        
        FutureCancel demo = new FutureCancel();
        demo.run();
    }
}
